### ISSUE TITLE
Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

### ISSUE THREAD

**Issue by vitskr** [vitskr/TfsStats#1]
Some mess with nugets

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.BuildHandler(VssCredentials credentials, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.TeamFoundation.WorkItemTracking.WebApi.WorkItemTrackingHttpClient..ctor(Uri baseUrl, VssCredentials credentials)
   at TfsStats.Program.main(String[] argv) in d:\workspace\fsharp\fsharpVSO\src\TfsStats.fs:line 8

**Comment by vitskr** [comment]
fixed
